a = 1
try:
    print(a)

except Exception as e:
    print(e)
else:
    print('no error')

print('hello')

